// Mock data - replace with actual data fetching
export const events = [
  {
    id: 1,
    date: "Nov 2",
    day: "Saturday",
    time: "12:00 AM",
    title: "Hacker Hotel",
    organizer: "Hacker Hotel, Lazar",
    location: "Location Shown Upon Approval",
    status: "Pending",
    isLive: true,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 2,
    date: "Nov 5",
    day: "Tuesday",
    time: "2:30 PM",
    title: "DevCon Workshop",
    organizer: "DevCon Team",
    location: "Bangkok Convention Center",
    status: "Confirmed",
    isLive: false,
    image: "/placeholder.svg?height=400&width=400",
  },
  {
    id: 3,
    date: "Nov 5",
    day: "Tuesday",
    time: "10:00 AM",
    title: "Networking Breakfast",
    organizer: "Tech Community BKK",
    location: "Sukhumvit Hotel",
    status: "Confirmed",
    isLive: false,
    image: "/placeholder.svg?height=400&width=400",
  },
];
